### ISSUE TITLE
Module data

### ISSUE THREAD

**Issue by mkarnebeek** [dave92082/SolarEdge-Exporter#11]
Hey Dave,

I was reading https://github.com/jbuehl/solaredge/issues/80#issuecomment-509495809 and wondered if you ever managed to pull module data from the Modbus-TCP data?

Kind regards,
Michiel

**Comment by dave92082** [comment]
Hey @mkarnebeek Sorry it took so long to get back. I haven't investigated much further into the module data but I don't think it's possible. It would be great to get access to it, but after having the solar running for a little over a year I've found myself looking less and less at the output data. I check SolarEdge's monitoring platform every now and then to make sure all my panels are still working since I haven't figured it out yet.
